//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	IcaaBearerAuthScopes = "icaaBearerAuth.Scopes"
	IcaaCookieAuthScopes = "icaaCookieAuth.Scopes"
)

// Defines values for ErrorCode.
const (
	AuthError            ErrorCode = "AuthError"
	BadRequest           ErrorCode = "BadRequest"
	InputValidationError ErrorCode = "InputValidationError"
	InternalError        ErrorCode = "InternalError"
	InvalidCursor        ErrorCode = "InvalidCursor"
	InvalidDateRange     ErrorCode = "InvalidDateRange"
	NotFound             ErrorCode = "NotFound"
)

// Address defines model for Address.
type Address struct {
	City       *string `json:"city"`
	Country    *string `json:"country"`
	Line1      *string `json:"line1"`
	Line2      *string `json:"line2"`
	PostalCode *string `json:"postalCode"`
	State      *string `json:"state"`
}

// AggregationItem defines model for AggregationItem.
type AggregationItem struct {
	// Count Number of donations in this aggregation
	Count int `json:"count"`

	// Country ISO 3166-1 alpha-2 country code
	Country string `json:"country"`
	Money   Money  `json:"money"`

	// State State or province code
	State string `json:"state"`
}

// BillingDetails defines model for BillingDetails.
type BillingDetails struct {
	Address *Address             `json:"address,omitempty"`
	Email   *openapi_types.Email `json:"email"`
	Name    *string              `json:"name"`
}

// CreateDonationRequest defines model for CreateDonationRequest.
type CreateDonationRequest struct {
	// Amount Amount in smallest currency unit (e.g., cents for USD)
	Amount int `json:"amount"`

	// Currency ISO 4217 currency code
	Currency   string              `json:"currency"`
	DonorEmail openapi_types.Email `json:"donorEmail"`
}

// CreateDonationResponse defines model for CreateDonationResponse.
type CreateDonationResponse struct {
	// ClientSecret Stripe PaymentIntent client secret for embedded checkout
	ClientSecret string `json:"clientSecret"`
}

// DonationAggregationResponse defines model for DonationAggregationResponse.
type DonationAggregationResponse struct {
	// Aggregations List of donation aggregations by location and currency
	Aggregations []AggregationItem `json:"aggregations"`
}

// DonationItem defines model for DonationItem.
type DonationItem struct {
	// Amount Amount in minor currency units
	Amount         int             `json:"amount"`
	BillingDetails *BillingDetails `json:"billingDetails,omitempty"`

	// CreatedAt When the donation was created
	CreatedAt time.Time `json:"createdAt"`

	// Currency ISO 4217 currency code
	Currency string `json:"currency"`

	// DonorEmail Email of the donor (if available)
	DonorEmail *openapi_types.Email `json:"donorEmail"`

	// Id Payment ID
	Id string `json:"id"`

	// Metadata Payment metadata
	Metadata *map[string]string `json:"metadata,omitempty"`

	// Status Payment status
	Status string `json:"status"`
}

// DonationListResponse defines model for DonationListResponse.
type DonationListResponse struct {
	// Items List of donations
	Items []DonationItem `json:"items"`

	// NextCursor Cursor for the next page (null if no more results)
	NextCursor *string `json:"nextCursor"`

	// TotalCount Total number of donations matching the filter (if available)
	TotalCount *int `json:"totalCount"`
}

// Error defines model for Error.
type Error struct {
	Code    ErrorCode `json:"code"`
	Message string    `json:"message"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// Money defines model for Money.
type Money struct {
	// Amount Amount in minor currency units (e.g., cents)
	Amount int `json:"amount"`

	// Currency ISO 4217 currency code
	Currency string `json:"currency"`
}

// GetDonationsV1Params defines parameters for GetDonationsV1.
type GetDonationsV1Params struct {
	// Limit Maximum number of donations to return (default 20, max 100)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Pagination cursor for fetching the next page
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`

	// CreatedAfter Filter donations created after this date (ISO 8601 format)
	CreatedAfter *time.Time `form:"created_after,omitempty" json:"created_after,omitempty"`

	// CreatedBefore Filter donations created before this date (ISO 8601 format)
	CreatedBefore *time.Time `form:"created_before,omitempty" json:"created_before,omitempty"`
}

// GetDonationsV1PerStateParams defines parameters for GetDonationsV1PerState.
type GetDonationsV1PerStateParams struct {
	// CreatedAfter Filter donations created after this date (ISO 8601 format)
	CreatedAfter *time.Time `form:"created_after,omitempty" json:"created_after,omitempty"`

	// CreatedBefore Filter donations created before this date (ISO 8601 format)
	CreatedBefore *time.Time `form:"created_before,omitempty" json:"created_before,omitempty"`
}

// PostDonationsV1JSONRequestBody defines body for PostDonationsV1 for application/json ContentType.
type PostDonationsV1JSONRequestBody = CreateDonationRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List donations
	// (GET /donations/v1)
	GetDonationsV1(w http.ResponseWriter, r *http.Request, params GetDonationsV1Params)
	// Create a donation
	// (POST /donations/v1)
	PostDonationsV1(w http.ResponseWriter, r *http.Request)
	// Get donation aggregations by state
	// (GET /donations/v1/per-state)
	GetDonationsV1PerState(w http.ResponseWriter, r *http.Request, params GetDonationsV1PerStateParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetDonationsV1 operation middleware
func (siw *ServerInterfaceWrapper) GetDonationsV1(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, IcaaCookieAuthScopes, []string{"admin"})

	ctx = context.WithValue(ctx, IcaaBearerAuthScopes, []string{"admin"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDonationsV1Params

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", r.URL.Query(), &params.Cursor)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	// ------------- Optional query parameter "created_after" -------------

	err = runtime.BindQueryParameter("form", true, false, "created_after", r.URL.Query(), &params.CreatedAfter)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created_after", Err: err})
		return
	}

	// ------------- Optional query parameter "created_before" -------------

	err = runtime.BindQueryParameter("form", true, false, "created_before", r.URL.Query(), &params.CreatedBefore)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created_before", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDonationsV1(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostDonationsV1 operation middleware
func (siw *ServerInterfaceWrapper) PostDonationsV1(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDonationsV1(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDonationsV1PerState operation middleware
func (siw *ServerInterfaceWrapper) GetDonationsV1PerState(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, IcaaCookieAuthScopes, []string{"admin"})

	ctx = context.WithValue(ctx, IcaaBearerAuthScopes, []string{"admin"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDonationsV1PerStateParams

	// ------------- Optional query parameter "created_after" -------------

	err = runtime.BindQueryParameter("form", true, false, "created_after", r.URL.Query(), &params.CreatedAfter)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created_after", Err: err})
		return
	}

	// ------------- Optional query parameter "created_before" -------------

	err = runtime.BindQueryParameter("form", true, false, "created_before", r.URL.Query(), &params.CreatedBefore)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created_before", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDonationsV1PerState(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/donations/v1", wrapper.GetDonationsV1)
	m.HandleFunc("POST "+options.BaseURL+"/donations/v1", wrapper.PostDonationsV1)
	m.HandleFunc("GET "+options.BaseURL+"/donations/v1/per-state", wrapper.GetDonationsV1PerState)

	return m
}

type GetDonationsV1RequestObject struct {
	Params GetDonationsV1Params
}

type GetDonationsV1ResponseObject interface {
	VisitGetDonationsV1Response(w http.ResponseWriter) error
}

type GetDonationsV1200JSONResponse DonationListResponse

func (response GetDonationsV1200JSONResponse) VisitGetDonationsV1Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDonationsV1400JSONResponse Error

func (response GetDonationsV1400JSONResponse) VisitGetDonationsV1Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetDonationsV1401JSONResponse Error

func (response GetDonationsV1401JSONResponse) VisitGetDonationsV1Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetDonationsV1403JSONResponse Error

func (response GetDonationsV1403JSONResponse) VisitGetDonationsV1Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetDonationsV1500JSONResponse Error

func (response GetDonationsV1500JSONResponse) VisitGetDonationsV1Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type PostDonationsV1RequestObject struct {
	Body *PostDonationsV1JSONRequestBody
}

type PostDonationsV1ResponseObject interface {
	VisitPostDonationsV1Response(w http.ResponseWriter) error
}

type PostDonationsV1200JSONResponse CreateDonationResponse

func (response PostDonationsV1200JSONResponse) VisitPostDonationsV1Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostDonationsV1400JSONResponse Error

func (response PostDonationsV1400JSONResponse) VisitPostDonationsV1Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostDonationsV1500JSONResponse Error

func (response PostDonationsV1500JSONResponse) VisitPostDonationsV1Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetDonationsV1PerStateRequestObject struct {
	Params GetDonationsV1PerStateParams
}

type GetDonationsV1PerStateResponseObject interface {
	VisitGetDonationsV1PerStateResponse(w http.ResponseWriter) error
}

type GetDonationsV1PerState200JSONResponse DonationAggregationResponse

func (response GetDonationsV1PerState200JSONResponse) VisitGetDonationsV1PerStateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDonationsV1PerState400JSONResponse Error

func (response GetDonationsV1PerState400JSONResponse) VisitGetDonationsV1PerStateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetDonationsV1PerState401JSONResponse Error

func (response GetDonationsV1PerState401JSONResponse) VisitGetDonationsV1PerStateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetDonationsV1PerState403JSONResponse Error

func (response GetDonationsV1PerState403JSONResponse) VisitGetDonationsV1PerStateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetDonationsV1PerState500JSONResponse Error

func (response GetDonationsV1PerState500JSONResponse) VisitGetDonationsV1PerStateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List donations
	// (GET /donations/v1)
	GetDonationsV1(ctx context.Context, request GetDonationsV1RequestObject) (GetDonationsV1ResponseObject, error)
	// Create a donation
	// (POST /donations/v1)
	PostDonationsV1(ctx context.Context, request PostDonationsV1RequestObject) (PostDonationsV1ResponseObject, error)
	// Get donation aggregations by state
	// (GET /donations/v1/per-state)
	GetDonationsV1PerState(ctx context.Context, request GetDonationsV1PerStateRequestObject) (GetDonationsV1PerStateResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetDonationsV1 operation middleware
func (sh *strictHandler) GetDonationsV1(w http.ResponseWriter, r *http.Request, params GetDonationsV1Params) {
	var request GetDonationsV1RequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDonationsV1(ctx, request.(GetDonationsV1RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDonationsV1")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDonationsV1ResponseObject); ok {
		if err := validResponse.VisitGetDonationsV1Response(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostDonationsV1 operation middleware
func (sh *strictHandler) PostDonationsV1(w http.ResponseWriter, r *http.Request) {
	var request PostDonationsV1RequestObject

	var body PostDonationsV1JSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostDonationsV1(ctx, request.(PostDonationsV1RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostDonationsV1")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostDonationsV1ResponseObject); ok {
		if err := validResponse.VisitPostDonationsV1Response(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDonationsV1PerState operation middleware
func (sh *strictHandler) GetDonationsV1PerState(w http.ResponseWriter, r *http.Request, params GetDonationsV1PerStateParams) {
	var request GetDonationsV1PerStateRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDonationsV1PerState(ctx, request.(GetDonationsV1PerStateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDonationsV1PerState")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDonationsV1PerStateResponseObject); ok {
		if err := validResponse.VisitGetDonationsV1PerStateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZbW/bOBL+KwTvPqSAbMtOk+0ZWOAcp114t2lzddMFtggCWhrbbCVSJakkvsL//TAU",
	"9WbTL100dwVu8yUWRc4MZ555Zkh9pZFMMylAGE2HX6mOlpAy+3MUxwq0/ZkpmYEyHOxTxM0K/4s8Sdgs",
	"ATo0KoeAmlUGdEi1UVws6DqgkcyFUcfNTbiA/tEzB0fNzKQ2LBnLGI6arg0zx8xcVyNy9gkig2tHi4WC",
	"BTNciomB1OM09AX+iEFHimc4kw7pmzydgSJyTmIp7HJNuCBmyTVhtUwaUHhkaYY2nVbquTCwALXh6raC",
	"yfQtOe2fn3f6hCXZknUGxM0lETqmIZjeTKnHLakUYAX/XcGcDunfejVkeg4vvSs7qenEthlTHCZSkUzJ",
	"ey4i2NZ+NaI+Vyv4knMFMR1+rHZZqimNc/unt57IXPAk4WJxCYbxxINmVsN83wbLbFgHFFLGE5w/lypl",
	"hg7dSHAYYoKlfxZhYwXMwKVDyTv4koM2nu2kfqCN7DhiS6csSUAbEuVKgYhWJBfckBPoLroBiXDXZC4V",
	"uZlePmsG6CwMw4CmXPA0T+mwj08eIDqhfiQ+H/R/qvV6AHjpQ2AshVQvS6/X0+34P91zN5IpDbZjsh9R",
	"zl0Nu1vqbo8IhM6k0ODJ+ISDMFOIFBhfQiieAblmqxSEmQgDwpBiCdF2jQ0CpDOIY4hJtITos8xNy18Z",
	"v+sPTp+fnf/04h/hXbHs7tH9Hc6mpoG+nZZ7bJDb7u022Epvb/c116bJck1y02S2IomM3AsRk0Ywqs1+",
	"rDj0tEF3BWdVFFWiv1+AtQajhVZNT0g266CSeHZY4uCQxHFL4qApcTzySdwSOB61BL59Q9e3AeUG0sPs",
	"tFF+agJhSrHVNuybwdoXen8xO0wyKRdStRlGN6PpArTNH7Mtut637w1yR/6x2RmPPNb9vgSsrFCD8IFp",
	"4ha08moQDp53wn6nf/a+Hw5Pw2EY/tHklpgZ6Biego+tnp4B21LtMOaW25pU5ITPCbtn3NaYFokfx5kH",
	"6xiPt+1wVEYml22OYqsGSXkbDDAsZoa5asxRHkuuW4jb9ohXdyXKA2nMq1zvttu9b9qu8ygCiC069nMp",
	"xym+YlJJrYG5L9+QJ3dzbMUF+8kV1R1FG60s3+KMgAp4NONcaam2lRbjtkgh8HAqydgCyAmih/A5EZKk",
	"UgFRoPPE6DYOYfVr9sd4cj4RF0v48OLx6tMVn//r55+PQZ+Rtq33UtB7fEeEp61OmYmWXCysuXOeGNiX",
	"KP2zcKclFV1tgsD6vOU2X6xfKlU4dPOEUJxT9gXMLrUHGps3WrMFtHuiibhnCY8bhbYE5aHW2jJRKXOn",
	"3eVpCgQ2gR8pdi5KsKTYVEAvWFz2pgF9I80rmQvMjYnIcvMBTbNmldNHuVmWv53pl8zAOyYWUA/Vzmxu",
	"tK14CyVXZcH9HrWr1R4/O6qSff86cLB33Y4a8h5EueJmNUUMOR6JGLsApkCh/3FkZp9elYXg19/f002O",
	"nYxHI8KiCLQmRn4Ggb7C9VLxfxdYWwKLAYNh8Yp2FHLrrSyNyWwBiRgbS/mZQ2nBIWWRnY3Mhu+rp+JE",
	"Zeffjcbjl9Pp3fu3v718U6tkGf8Nz6boCy7m0hN6QUbXE0tlqDIzyBI1cRhJrDn3nJGibe+idG6SUjMp",
	"iRTl0IDeg9KF6H437Ia4YZmBYBmnQ3pqhwKaMbO00ehVqnr39gpk4TswjOKUi44UyYqAiDPJhUHLEuR+",
	"liQNex+4WSIV82IAjcUEKJg+pkP6C5jSYP2hb01RLAUDSts+u634ij3iic/LqUYSBSZXgpzEMGd5Ysgg",
	"DEjKHkk/DJ+V0fqSgz21u2AlPOWmRAkrtmoX0+EAj5iFQnfErA+cPv7dLubltjG5ygI1hwb1V5Vqh3XF",
	"upZ5W3m4qfZVUU5qx7hqT9gcx+11DjaN5ARz/8V52CdF07XLRW79nV3fsuWYJvQbDJzBHGv0n7ewEPDt",
	"Jt4imRWNjs2CQRgWVdAehS1TZ1nCi1Nh75PGbXxtKDmmr2l1U5YADjRODs0QE9v6aT3Pk2TVxQR+/h3t",
	"K2qWx6CyetcJWRYe7t4U6HzmTOo/vUk3gjmOh5h0SMq1xkySqjIJ34MwTq+z7PTpLXsl1YzHMQjSIbkG",
	"RbgmQhrCBGFIltaSs/9G2G7EZyEfBNGg7kERwHndVvG1vLpZ9D5Saye9xXzdrMn1y9uA6jxNmb1LsJCt",
	"G313y+1pz216asKIgIdGNyhih3F85S6hyrslokFj3SI3715vV41rqTfKhioavQsZr76bj/3XnB6fVyU3",
	"dof/ZnOE7fr6CQlmxx2gx8zxpm9L4v3fEMwFw/hbp/5g6dFCeeFfwirg2tmtRqmXgepUXxu+pWUqL7+g",
	"wfuzVfVZBFPEyu2V3yoOdVDXoKbue8TeTuqvLuGH7BJ819seFDemlVcaP0q7YEOi8MxMTtoex5rofrXA",
	"8lcD8f/aQPwCZvdXmIJP14ViNMVHY9dKxnlk1xeTaEBzlbjTvR72eizjXTSn+yBVEvfoNtO8lhFLSAz3",
	"PhHDXi/B90upzfA0DMMeXd+u/xMAAP//Brt+UqsgAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
