//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	GoogleBearerAuthScopes = "googleBearerAuth.Scopes"
	GoogleCookieAuthScopes = "googleCookieAuth.Scopes"
)

// Defines values for ErrorCode.
const (
	AuthError            ErrorCode = "AuthError"
	BadRequest           ErrorCode = "BadRequest"
	InputValidationError ErrorCode = "InputValidationError"
	InternalError        ErrorCode = "InternalError"
	InvalidDateRange     ErrorCode = "InvalidDateRange"
	NotFound             ErrorCode = "NotFound"
)

// AggregationItem defines model for AggregationItem.
type AggregationItem struct {
	// Count Number of donations in this aggregation
	Count int `json:"count"`

	// Country ISO 3166-1 alpha-2 country code
	Country string `json:"country"`
	Money   Money  `json:"money"`

	// State State or province code
	State string `json:"state"`
}

// CreateDonationRequest defines model for CreateDonationRequest.
type CreateDonationRequest struct {
	// Amount Amount in smallest currency unit (e.g., cents for USD)
	Amount int `json:"amount"`

	// Currency ISO 4217 currency code
	Currency   string              `json:"currency"`
	DonorEmail openapi_types.Email `json:"donorEmail"`
}

// CreateDonationResponse defines model for CreateDonationResponse.
type CreateDonationResponse struct {
	// ClientSecret Stripe PaymentIntent client secret for embedded checkout
	ClientSecret string `json:"clientSecret"`
}

// DonationAggregationResponse defines model for DonationAggregationResponse.
type DonationAggregationResponse struct {
	// Aggregations List of donation aggregations by location and currency
	Aggregations []AggregationItem `json:"aggregations"`
}

// Error defines model for Error.
type Error struct {
	Code    ErrorCode `json:"code"`
	Message string    `json:"message"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// Money defines model for Money.
type Money struct {
	// Amount Amount in minor currency units (e.g., cents)
	Amount int `json:"amount"`

	// Currency ISO 4217 currency code
	Currency string `json:"currency"`
}

// GetDonationsV1PerStateParams defines parameters for GetDonationsV1PerState.
type GetDonationsV1PerStateParams struct {
	// CreatedAfter Filter donations created after this date (ISO 8601 format)
	CreatedAfter *time.Time `form:"created_after,omitempty" json:"created_after,omitempty"`

	// CreatedBefore Filter donations created before this date (ISO 8601 format)
	CreatedBefore *time.Time `form:"created_before,omitempty" json:"created_before,omitempty"`
}

// PostDonationsV1JSONRequestBody defines body for PostDonationsV1 for application/json ContentType.
type PostDonationsV1JSONRequestBody = CreateDonationRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create a donation
	// (POST /donations/v1)
	PostDonationsV1(w http.ResponseWriter, r *http.Request)
	// Get donation aggregations by state
	// (GET /donations/v1/per-state)
	GetDonationsV1PerState(w http.ResponseWriter, r *http.Request, params GetDonationsV1PerStateParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// PostDonationsV1 operation middleware
func (siw *ServerInterfaceWrapper) PostDonationsV1(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostDonationsV1(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDonationsV1PerState operation middleware
func (siw *ServerInterfaceWrapper) GetDonationsV1PerState(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, GoogleCookieAuthScopes, []string{"admin"})

	ctx = context.WithValue(ctx, GoogleBearerAuthScopes, []string{"admin"})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetDonationsV1PerStateParams

	// ------------- Optional query parameter "created_after" -------------

	err = runtime.BindQueryParameter("form", true, false, "created_after", r.URL.Query(), &params.CreatedAfter)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created_after", Err: err})
		return
	}

	// ------------- Optional query parameter "created_before" -------------

	err = runtime.BindQueryParameter("form", true, false, "created_before", r.URL.Query(), &params.CreatedBefore)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "created_before", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDonationsV1PerState(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("POST "+options.BaseURL+"/donations/v1", wrapper.PostDonationsV1)
	m.HandleFunc("GET "+options.BaseURL+"/donations/v1/per-state", wrapper.GetDonationsV1PerState)

	return m
}

type PostDonationsV1RequestObject struct {
	Body *PostDonationsV1JSONRequestBody
}

type PostDonationsV1ResponseObject interface {
	VisitPostDonationsV1Response(w http.ResponseWriter) error
}

type PostDonationsV1200JSONResponse CreateDonationResponse

func (response PostDonationsV1200JSONResponse) VisitPostDonationsV1Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostDonationsV1400JSONResponse Error

func (response PostDonationsV1400JSONResponse) VisitPostDonationsV1Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostDonationsV1500JSONResponse Error

func (response PostDonationsV1500JSONResponse) VisitPostDonationsV1Response(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetDonationsV1PerStateRequestObject struct {
	Params GetDonationsV1PerStateParams
}

type GetDonationsV1PerStateResponseObject interface {
	VisitGetDonationsV1PerStateResponse(w http.ResponseWriter) error
}

type GetDonationsV1PerState200JSONResponse DonationAggregationResponse

func (response GetDonationsV1PerState200JSONResponse) VisitGetDonationsV1PerStateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetDonationsV1PerState400JSONResponse Error

func (response GetDonationsV1PerState400JSONResponse) VisitGetDonationsV1PerStateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetDonationsV1PerState401JSONResponse Error

func (response GetDonationsV1PerState401JSONResponse) VisitGetDonationsV1PerStateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetDonationsV1PerState403JSONResponse Error

func (response GetDonationsV1PerState403JSONResponse) VisitGetDonationsV1PerStateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetDonationsV1PerState500JSONResponse Error

func (response GetDonationsV1PerState500JSONResponse) VisitGetDonationsV1PerStateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Create a donation
	// (POST /donations/v1)
	PostDonationsV1(ctx context.Context, request PostDonationsV1RequestObject) (PostDonationsV1ResponseObject, error)
	// Get donation aggregations by state
	// (GET /donations/v1/per-state)
	GetDonationsV1PerState(ctx context.Context, request GetDonationsV1PerStateRequestObject) (GetDonationsV1PerStateResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// PostDonationsV1 operation middleware
func (sh *strictHandler) PostDonationsV1(w http.ResponseWriter, r *http.Request) {
	var request PostDonationsV1RequestObject

	var body PostDonationsV1JSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostDonationsV1(ctx, request.(PostDonationsV1RequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostDonationsV1")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostDonationsV1ResponseObject); ok {
		if err := validResponse.VisitPostDonationsV1Response(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetDonationsV1PerState operation middleware
func (sh *strictHandler) GetDonationsV1PerState(w http.ResponseWriter, r *http.Request, params GetDonationsV1PerStateParams) {
	var request GetDonationsV1PerStateRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetDonationsV1PerState(ctx, request.(GetDonationsV1PerStateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetDonationsV1PerState")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetDonationsV1PerStateResponseObject); ok {
		if err := validResponse.VisitGetDonationsV1PerStateResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xX3XLbNhN9Fcx+30UyQ4uSFTspryrLsavWiT1RnF54PB6IWElISIABQCVqRu/eWfBH",
	"ZMhUybRJqysRBM6e/TtYfoJYp5lWqJyF6BPYeI0p938nq5XBFXdSq5nDlJYyozM0TqLfEOtcOfoj0MZG",
	"ZrQTIniZpws0TC+Z0Moft0wq5tbSMr7HhADwI0+zBCEaB+C2GUIEUjlcoYFdUMCbbdfAbH7NxqPT06MR",
	"40m25kfHrNzLYi2wCQy3c6ixrTNSrQg61Qo98P8NLiGC/4X7KIRlCMIXftMuAOu4wy6NOS0zbVhm9Eaq",
	"GLvWX0y61ncBGHyfS4MCorvay8pMRa70H+5rAL14i7EjQlOD3OF5Gd1X+D5H67r54Wl/giZ+nXJiU54k",
	"aB2Lc2NQxVuWK+nYIxysBgGLKRxsqQ27nZ8/bjp2MhwOA0ilkmmeQjSip54ElqD9GXxyPHq6t9uTuPO+",
	"zAmttHmecpkQ6n67X/+5fB7EOoUAltqk3EEE6PcfykQZrgbvlrmvSYTNtLLY0ymJROXmGBt0fYVkZIbs",
	"hm9TVG6mHCrHiiPM+jM+CZguUAgULF5j/E7nrhWvTD6MjsdPTk6fPvtp+FAce/hY/g5XYZNgn6eVjw1R",
	"+LK7jS63XXevpHVNdWiKgmWLLUt0XL5QgjWSUTt7V2vPuCETRa/XrV1V/6go1n0x+tLatzU16S6oEU8O",
	"Ix4fQpy2EI+biNNJH2IHcDppAV6/hN19ANJhag/J1ueyvauzyY3h227ZN5PVl/rnxmjTp/4CD3HxR6e0",
	"kUQXreUrbPftTG14IkWjGKouPCSbXi8qzC/ynpYsUZFQ3QF1l1E8KZwK4IyLSj8DeKndhc6VgABmKsvd",
	"G6LmaVXbJ7lbV/9L6ufc4SuuChJNx9qGOkr2oiqCbxXtVCpt2optW5Ldkuqy/H+EOh/U026WqMYxzo10",
	"2znVTBGDldarBM+QGzQUcVpb+KeLStJ//f01XZn+DETl2z2ltXMZOVkgTbV+J7FCkuRj7JcgAMU9wOX1",
	"9eXV84fJ7etfHgrsqmky+RuNAURVqqXuyYxik5uZl2gex5g5qVaN0cdpNptOJmwjOSuUfkDo0hVlQq8q",
	"cSUcCGCDxhbQo8FwMCQ/dIaKZxIiGPulADLu1j5YYW0q3Ix8PWnbUz/FVWUZZwo/NNpNCWbQ5UbRq/Im",
	"qi4YZtESE3b76opIU50WwiIgghttXcXcvhlBkX207kyLbaEQ/irzVZ1liSxUPXxriVA1ah6SkP5Zx6ej",
	"7WAdRIGOy8RCsxqdydGXZ3Fl+cAdD4ffjWV5M/bQnH4e29gfFczmcYzWLvMk2Q4o50/+QX6FCvXQOeOU",
	"fx9Ub/TkRxi9Ve+U/qCYRbNBw5D2DVpiANHdfQA2T1NeXJs+SIzXhet3t0o/zNAc1aP6qm/QmohUqiOt",
	"ki1DJTItlaP2rG5AbHTtYlt/U1CLeNywGvS7vXCJzVa4QTMvh/mMG56iQ2P92NLmcyETh6ZhtaoFvqR1",
	"/8UkiNcjkuRnp8MRK2ZaUngvY+9z9N8OpYqV5x/8+UoffZ7qWZjwjpxMsU+/v5rgApfa4N9gWAB8O8X7",
	"79jEfzXj9lRxYxszaPPE2VJK/7VurqcpSomhoYQ9akecSVslr1Usj0uSox/R/Tx3a23kHyjYEUultXRj",
	"asNkSZ/eo3Kl3ZLZ+Pszu9BmIYVAxY5YbtFQsJR2jCvGSTr+Ywr5qWe8uQPPFO6pmbtz1P51S14v0X35",
	"c6zQ1F1hnOj0SdmN0SKP/fliEwSQm6QcxWwUhjyTAxlzPvigTSJC6KrNlY55wgRu+iCiMKTvwmStrYvG",
	"w+EwhN397s8AAAD//4Fhdr+/EgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
